dist: trusty
sudo: false
language: python
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.6"
    - python: "3.5"
    - python: "3.4"
    - python: "2.7"
env:
  - CPPFLAGS=--coverage
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y libpoppler-cpp-dev pkg-config
  - pip install cpp-coveralls
script: python setup.py test
after_success: coveralls --build-root .
