dist: trusty
sudo: required
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpoppler-cpp-dev pkg-config
script: python setup.py test
