dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
env:
  - CPPFLAGS=--coverage
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpoppler-cpp-dev pkg-config
  - pip install cpp-coveralls
script: python setup.py test
after_success: coveralls --build-root .
