language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"

env: CPPFLAGS=--coverage

before_install:
  - sudo apt-get update
  - sudo apt-get install --yes libpoppler-cpp-dev pkg-config

before_script:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == "3.7" ]]; then
    pip install black cpp-coveralls
    fi

script:
  - python setup.py test
  - |
    if [[ $TRAVIS_PYTHON_VERSION == "3.7" ]]; then
    black --check .
    fi

after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == "3.7" ]]; then
    coveralls --build-root .
    fi
