dist: trusty
sudo: required
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - CPPFLAGS=--coverage
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y libpoppler-cpp-dev pkg-config
  - pip install cpp-coveralls
script: python setup.py test
after_success: coveralls --build-root .
